# Generated by Django 5.1.4 on 2024-12-18 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_snippet_highlighted_snippet_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='created_at',
            field=models.DateTimeField(blank=True, db_default=datetime.datetime(2024, 12, 18, 18, 39, 8, 558116), default=datetime.datetime(2024, 12, 18, 18, 39, 8, 558116)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(blank=True, db_default=datetime.datetime(2024, 12, 18, 18, 39, 8, 557055), default=datetime.datetime(2024, 12, 18, 18, 39, 8, 556037)),
        ),
    ]
