# Generated by Django 5.1.4 on 2024-12-10 14:12

import datetime
import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('age', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, db_default=datetime.datetime(2024, 12, 10, 19, 42, 43, 335593), default=datetime.datetime(2024, 12, 10, 19, 42, 43, 335593))),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, db_default=datetime.datetime(2024, 12, 10, 19, 42, 43, 336573), default=datetime.datetime(2024, 12, 10, 19, 42, 43, 336573))),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UI.user')),
            ],
        ),
    ]
