# Generated by Django 5.1.4 on 2024-12-13 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0002_alter_user_created_at_snippet_delete_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='description',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='snippet',
            name='created_at',
            field=models.DateTimeField(blank=True, db_default=datetime.datetime(2024, 12, 13, 11, 57, 45, 92910), default=datetime.datetime(2024, 12, 13, 11, 57, 45, 92910)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(blank=True, db_default=datetime.datetime(2024, 12, 13, 11, 57, 45, 92910), default=datetime.datetime(2024, 12, 13, 11, 57, 45, 92910)),
        ),
    ]
