# Generated by Django 5.1.4 on 2024-12-13 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0003_rename_description_snippet_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='posted_by',
        ),
        migrations.AlterField(
            model_name='snippet',
            name='created_at',
            field=models.DateTimeField(blank=True, db_default=datetime.datetime(2024, 12, 13, 17, 7, 7, 631620), default=datetime.datetime(2024, 12, 13, 17, 7, 7, 631620)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(blank=True, db_default=datetime.datetime(2024, 12, 13, 17, 7, 7, 631620), default=datetime.datetime(2024, 12, 13, 17, 7, 7, 631620)),
        ),
    ]
